[features]
seeds = false
skip-lint = false
[programs.localnet]
tic_tak_toe = "DFUVqtTDCXTywA7ELfN6WwXv6Gcw7UqK2WkVJK8rvzd7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ferrislav/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
